CREATE DATABASE reddit;
USE reddit;

CREATE TABLE posts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  timestamp BIGINT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(id));

CREATE TABLE users (
  user_id BIGINT NOT NULL AUTO_INCREMENT,
  user_name VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(20) NOT NULL,
  PRIMARY KEY(user_id));

ALTER TABLE posts ADD user_id BIGINT NOT NULL;